### ISSUE TITLE
Improve User Experience for Theme Selection

### ISSUE THREAD

**Issue by Blackarrow299** [The-Embassy-Collective/athan#22]
Issue Summary:
In the current version of the app, when users want to change the theme using the radio buttons (dark, light), they are required to save the changes before seeing the preview

Expected Behavior:
After selecting a different theme option, the app should immediately provide a live preview of the chosen theme without requiring users to save the change first.

**Comment by Stormix** [comment]
It's currently not feasible with the way we have the global store setup. i.e, when you set the theme, it's persisted immediately, if we want to achieve this behavior, we need a separate temporary state that also controls the theme, **but that is not persisted**.

So unless, someone else takes a look into this, I don't think it's worth the effort.

Thank you however for the idea and your contribution.
