### ISSUE TITLE
Improve  Experience for Location Setup 

### ISSUE THREAD

**Issue by Blackarrow299** [The-Embassy-Collective/athan#25]
Issue Summary:
When a user enters the app for the first time, it currently starts on the Settings Page without any clear guidance on the importance of setting a location and saving it. Additionally, the prayer button on the sidebar is non-functional until the location is set and saved. This can lead to confusion .

Steps to Reproduce:
.Launch the app for the first time.
.Observe that it starts on the Settings Page by default.
.Attempt to click on the prayer button in the sidebar, note that it does not work.

Expected Behavior:
 users should see a clear message guiding them to set their location and save it.

**Comment by Stormix** [comment]
I added a small toast on the settings page when you open it for the first time. Hope that makes it clearer, feel free to re-open if you think the current solution is not sufficient.
