### ISSUE TITLE
What if i live in France Marseille

### ISSUE THREAD

**Issue by Blackarrow299** [The-Embassy-Collective/athan#28]
Issue Description:
The default location is set to "France, Marseille." Upon entering the application for the first time, users find that they are unable to save this default location until they manually modify another input field. This behavior becomes problematic for users who are actually residing in Marseille, as they have to modify an input field to enable the save option.

Steps to Reproduce:
1.Open the application for the first time.
2.Observe that the default location is set to "France, Marseille."
3.Attempt to save the default location without modifying any other input fields.
4.Note that the save option is disabled and not functional.
5.Manually modify an unrelated input field.
6.Observe that the save option becomes enabled.
7.Save the default location.

**Comment by Blackarrow299** [comment]
I'd like to take on this issue.

**Comment by Stormix** [comment]
Go for it, I think lmouchkil men dik isDirty
