### ISSUE TITLE
Notifications timing/Call for prayer bug 

### ISSUE THREAD

**Issue by aL0NEW0LF** [The-Embassy-Collective/athan#47]
**Describe the bug**
I don't know if it's a bug or a feature, but when you setup a reminder in the settings, let's say 5min, the app tells you that it's prayer time and calls for prayer at that reminder time, not the actual prayer time.

**Expected behavior**
The app should push a notification that tells you how much time left before the prayer (the reminder you have setup) like: 5 minutes before Asr, then at prayer time it should tell you that it's prayer time like: It's time for Asr, and actually calls for the prayer.

**Comment by Stormix** [comment]
That is correct! Good catch!
