### ISSUE TITLE
App keep Crashing...

### ISSUE THREAD

**Issue by MrEmaad** [The-Embassy-Collective/athan#49]
Every time I open the app, it crashes immediately.

I have attempted to install it using different versions (.exe and .msi). Initially, when I installed it with the .msi file, the application run without any issues. However, after I restarted my computer, it started crashing again....

**Comment by aL0NEW0LF** [comment]
What actions lead to the crash? Is it immediately after you open it it crashes, or you trigger something specific to cause the crash?

Also can you tell us your OS version and hardware specs if you don't mind.

**Comment by MrEmaad** [comment]
yes it s immediately after i open it , im using Windows 10 21H1.
